apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.20.2
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 10m0s
  releaseName: cloudnative-pg
  storageNamespace: cnpg-system
  targetNamespace: cnpg-system
  values:
    monitoring:
      podMonitorEnabled: true
