apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 50.3.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: kube-prometheus-stack
  storageNamespace: prometheus
  targetNamespace: prometheus
  values:
    alertmanager:
      alertmanagerSpec:
        alertmanagerConfiguration:
          name: global-alertmanagerconfig
    prometheus:
      prometheusSpec:
        podMonitorSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
