apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- cloudnative-pg-release.yaml
- ingress-nginx-release.yaml
- kube-prometheus-stack-release.yaml
